name: Build Container Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        if [[ ${{ github.event.head_commit.message }} == *'BUILD_CONTAINER_IMAGE'* ]]; then
          docker build -t rushikesh11/guestbook-go:latest
        fi
      env:
        DOCKER_BUILDKIT: 1

    - name: Push Docker Image
      if: github.event.head_commit.message == 'BUILD_CONTAINER_IMAGE' || github.event.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push rushikesh11/guestbook-go:latest
